export enum QUERY_KEYS {
  GET_AUTHENTICATED_USER = "GET_AUTHENTICATED_USER",

  GET_BATTLEGROUND_CARDS = "GET_BATTLEGROUND_CARDS",

  GET_MY_COMPS = "GET_MY_COMPS",
  GET_COMP_BY_ID = "GET_COMP_BY_ID",
}
